// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jabardigitalservice/portal-jabar-services/core-service/src/domain"
	mock "github.com/stretchr/testify/mock"
)

// FeedbackUsecase is an autogenerated mock type for the FeedbackUsecase type
type FeedbackUsecase struct {
	mock.Mock
}

// Store provides a mock function with given fields: _a0, _a1
func (_m *FeedbackUsecase) Store(_a0 context.Context, _a1 *domain.Feedback) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Feedback) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewFeedbackUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewFeedbackUsecase creates a new instance of FeedbackUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFeedbackUsecase(t mockConstructorTestingTNewFeedbackUsecase) *FeedbackUsecase {
	mock := &FeedbackUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
