// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jabardigitalservice/portal-jabar-services/core-service/src/domain"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// EventRepository is an autogenerated mock type for the EventRepository type
type EventRepository struct {
	mock.Mock
}

// AgendaPortal provides a mock function with given fields: ctx, params
func (_m *EventRepository) AgendaPortal(ctx context.Context, params *domain.Request) ([]domain.Event, int64, error) {
	ret := _m.Called(ctx, params)

	var r0 []domain.Event
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Request) []domain.Event); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Request) int64); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *domain.Request) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Delete provides a mock function with given fields: ctx, id
func (_m *EventRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx, params
func (_m *EventRepository) Fetch(ctx context.Context, params *domain.Request) ([]domain.Event, int64, error) {
	ret := _m.Called(ctx, params)

	var r0 []domain.Event
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Request) []domain.Event); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Request) int64); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *domain.Request) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *EventRepository) GetByID(ctx context.Context, id int64) (domain.Event, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.Event
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Event); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Event)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTitle provides a mock function with given fields: ctx, title
func (_m *EventRepository) GetByTitle(ctx context.Context, title string) (domain.Event, error) {
	ret := _m.Called(ctx, title)

	var r0 domain.Event
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Event); ok {
		r0 = rf(ctx, title)
	} else {
		r0 = ret.Get(0).(domain.Event)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTx provides a mock function with given fields: ctx
func (_m *EventRepository) GetTx(ctx context.Context) (*sql.Tx, error) {
	ret := _m.Called(ctx)

	var r0 *sql.Tx
	if rf, ok := ret.Get(0).(func(context.Context) *sql.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCalendar provides a mock function with given fields: ctx, params
func (_m *EventRepository) ListCalendar(ctx context.Context, params *domain.Request) ([]domain.Event, error) {
	ret := _m.Called(ctx, params)

	var r0 []domain.Event
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Request) []domain.Event); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Request) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, body, tx
func (_m *EventRepository) Store(ctx context.Context, body *domain.StoreRequestEvent, tx *sql.Tx) error {
	ret := _m.Called(ctx, body, tx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StoreRequestEvent, *sql.Tx) error); ok {
		r0 = rf(ctx, body, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, id, body, tx
func (_m *EventRepository) Update(ctx context.Context, id int64, body *domain.StoreRequestEvent, tx *sql.Tx) error {
	ret := _m.Called(ctx, id, body, tx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *domain.StoreRequestEvent, *sql.Tx) error); ok {
		r0 = rf(ctx, id, body, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEventRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewEventRepository creates a new instance of EventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEventRepository(t mockConstructorTestingTNewEventRepository) *EventRepository {
	mock := &EventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
