// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jabardigitalservice/portal-jabar-services/core-service/src/domain"
	mock "github.com/stretchr/testify/mock"
)

// UptdCabdinRepository is an autogenerated mock type for the UptdCabdinRepository type
type UptdCabdinRepository struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx
func (_m *UptdCabdinRepository) Fetch(ctx context.Context) ([]domain.UptdCabdin, error) {
	ret := _m.Called(ctx)

	var r0 []domain.UptdCabdin
	if rf, ok := ret.Get(0).(func(context.Context) []domain.UptdCabdin); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UptdCabdin)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUptdCabdinRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUptdCabdinRepository creates a new instance of UptdCabdinRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUptdCabdinRepository(t mockConstructorTestingTNewUptdCabdinRepository) *UptdCabdinRepository {
	mock := &UptdCabdinRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
