DROP TABLE IF EXISTS informations;
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS units;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS areas;
DROP TABLE IF EXISTS feedback;
DROP TABLE IF EXISTS featured_programs;
