BEGIN;
ALTER TABLE news ADD highlight tinyint(1) NOT NULL DEFAULT 0 AFTER views;
ALTER TABLE news MODIFY created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE news MODIFY updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
COMMIT;