BEGIN;
ALTER TABLE news DROP COLUMN highlight;
ALTER TABLE news MODIFY created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE news MODIFY updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
COMMIT;