BEGIN;
ALTER TABLE news CHANGE author_id author VARCHAR(100);
ALTER TABLE news ADD COLUMN reporter VARCHAR(100) NULL AFTER author;
ALTER TABLE news ADD COLUMN editor VARCHAR (100) NULL AFTER reporter;
COMMIT;