CREATE TABLE `main_services` (
    `id` int(10) PRIMARY KEY AUTO_INCREMENT,
    `opd_name` int(10) unsigned,
    `government_affair` varchar(255),
    `sub_government_affair` varchar(255),
    `service_form` varchar(100),
    `service_type` varchar(50),
    `sub_service_type` varchar(255),
    `service_name` varchar(150),
    `program_name` varchar(100),
    `description` text,
    `service_user` varchar(50),
    `sub_service_spbe` varchar(50),
    `operational_status` varchar(30),
    `technical` varchar(30),
    `benefits` varchar(255),
    `facilities` varchar(255),
    `website` varchar(100),
    `links` json,
    `terms_and_condition` varchar(255),
    `service_procedures` varchar(255),
    `service_fee` varchar(30),
    `operational_time` json,
    `hotline_number` varchar(30),
    `hotline_mail` varchar(100),
    `location` json
);
