CREATE TABLE `service_informations` (
    `id` int(10) PRIMARY KEY AUTO_INCREMENT,
    `opd_name` int(10) unsigned,
    `government_affair` varchar(255),
    `sub_government_affair` varchar(255),
    `form` varchar(100),
    `type` varchar(50),
    `sub_service_type` varchar(255),
    `name` varchar(150),
    `program_name` varchar(100),
    `description` text,
    `user` varchar(50),
    `sub_service_spbe` varchar(50),
    `operational_status` varchar(30),
    `technical` varchar(30),
    `benefits` varchar(255),
    `facilities` varchar(255),
    `website` varchar(100),
    `links` json,
    FOREIGN KEY (`opd_name`) REFERENCES `units` (`id`)
);
